# Generated by Django 2.2.9 on 2021-01-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kansas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='per_portion_calories',
            new_name='calories_pp',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='per_portion_carbs',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='per_portion_fat',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='per_portion_fibre',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='per_portion_protein',
        ),
        migrations.AddField(
            model_name='recipe',
            name='grams_carbs_pp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grams_fat_pp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grams_fibre_pp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grams_protein_pp',
            field=models.FloatField(default=0),
        ),
    ]
