# Generated by Django 2.2.9 on 2021-02-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kansas', '0004_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='grams_fibre_pp',
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='D', max_length=9),
        ),
    ]
